Nama = input("Nama Lengkap :")
NamaPanggilan = input("Nama Panggilan :")
NPM = input("NPM :")
TempatLahir = input("Tempat Lahir :")
Umur = input("Umur :")
Alamat = input("Alamat :")
NomorTelfon = input("Telepon :")
print ("Assalamu'alaikum ")
print ("Let me introduce my self. My name is" ,Nama, ",but you can call me " ,NamaPanggilan, ", My NPM is" ,NPM, ". I was born in" ,TempatLahir, ",and I am" ,Umur, "years old" ".I am very glad if you want to invite my house in" ,Alamat, "So, don't forget to call me before with the number" ,NomorTelfon,)
print("Thank you.")